if(LINUX OR ANDROID)
  file(GLOB ROCM_NATIVE_LIBRARY_PATH "/opt/rocm/lib/libamdhip64.so")
  file(GLOB ROCM_INCLUDE_DIR "/opt/rocm/include")
elseif(WIN32)
  set(ROCM_HIP_DIR ${HIP_PATH})
  if (DEFINED $ENV{HIP_PATH})
    set(ROCM_HIP_DIR $ENV{HIP_PATH})
    message(STATUS "Bicudo is using HIP_PATH venv")
  endif()
  file(GLOB ROCM_INCLUDE_DIR "${ROCM_HIP_DIR}/include")
endif()
